stages:
  data_download:
    cmd: python src/data_loader.py
    deps:
      - src/data_loader.py
    outs:
      - data/cats_and_dogs:
          cache: true

  data_preprocess:
    cmd: python src/data_preprocessing.py
    deps:
      - data/cats_and_dogs
      - src/data_preprocessing.py
    outs:
      - data/cats_and_dogs/train:
          cache: false
      - data/cats_and_dogs/val:
          cache: false
      - data/cats_and_dogs/test:
          cache: false

  train_model:
    cmd: python src/train_cnn.py
    deps:
      - data/cats_and_dogs
      - src/train_cnn.py
      - src/data_preprocessing.py
    outs:
      - artifacts/model.h5:
          cache: true
    metrics:
      - artifacts/metrics.json:
          cache: false
    params:
      - train_config:
          - epochs
          - batch_size
          - learning_rate
