stages:
  data_download:
    cmd: python src/data_loader.py
    deps:
      - src/data_loader.py
      - src/kaggle.json
    outs:
      - data/cat-and-dog.zip

  data_extraction:
    cmd: python src/data_loader.py
    deps:
      - src/data_loader.py
      - data/cat-and-dog.zip
    outs:
      - data/training_set
      - data/test_set

  data_organization:
    cmd: python src/data_loader.py
    deps:
      - src/data_loader.py
      - data/training_set
      - data/test_set
    outs:
      - data/train
      - data/validation
      - data/test

  model_training:
    cmd: python src/train_cnn.py
    deps:
      - src/train_cnn.py
      - src/data_preprocessing.py
      - src/main.py
      - data/train
      - data/validation
      - data/test
    params:
      - epochs
      - batch_size
      - learning_rate
    outs:
      - models/mobilenet_v2.keras
    metrics:
      - metrics.json:
          cache: false
